mutation createDistrict($name: String!, $geoJson: GeoJSONMultiPolygon!) {
    createDistrict(name: $name, geoJson: $geoJson) {
        id
        name
        candidates {
            id
            name
            picture {
                filename
                location
                mimetype
            }
            politicalParty {
                id
                name
                colour
                logo {
                    filename
                    location
                    mimetype
                }
            }
        }
        geoJson
    }
}
