"""Initial data.

Revision ID: 0a112a1a9fe8
Revises: 
Create Date: 2020-03-08 04:53:55.579471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a112a1a9fe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvote_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('auth_factors', postgresql.ARRAY(sa.Enum('totp', 'recognition', name='optionalauthfactor')), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('voter', 'election_officer', 'administrator', name='roleenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvote_user_email'), 'canvote_user', ['email'], unique=True)
    op.create_index(op.f('ix_canvote_user_first_name'), 'canvote_user', ['first_name'], unique=False)
    op.create_index(op.f('ix_canvote_user_id'), 'canvote_user', ['id'], unique=False)
    op.create_index(op.f('ix_canvote_user_last_name'), 'canvote_user', ['last_name'], unique=False)
    op.create_index(op.f('ix_canvote_user_role'), 'canvote_user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canvote_user_role'), table_name='canvote_user')
    op.drop_index(op.f('ix_canvote_user_last_name'), table_name='canvote_user')
    op.drop_index(op.f('ix_canvote_user_id'), table_name='canvote_user')
    op.drop_index(op.f('ix_canvote_user_first_name'), table_name='canvote_user')
    op.drop_index(op.f('ix_canvote_user_email'), table_name='canvote_user')
    op.drop_table('canvote_user')
    # ### end Alembic commands ###
