const resolversList = [
  'addVoter',
  'getVoters',
  'getVoter',
  'getVoterByEmail',
  'addVote',
  'getVotes',
  'getVote',
  'getPoliticalPartyCandidates',
  'getPoliticalPartyCandidate',
  'addPoliticalPartyCandidate',
  'updatePoliticalPartyCandidate',
  'deletePoliticalPartyCandidate',
  'getPoliticalParties',
  'getPoliticalParty',
  'getPoliticalPartyByName',
  'addPoliticalParty',
  'updatePoliticalParty',
  'deletePoliticalParty',
  'addDistrict',
  'getDistrict',
  'getDistricts',
  'getDistrictByName',
  'updateDistrict',
  'deleteDistrict',
  'addBallot',
  'getBallots',
  'getBallot',
  'getBallotByCandidate',
];

module.exports = { resolversList };
