# Persistent Volume Claim - K8s Configuration
# https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canvote-pvc
  namespace: canvote
spec:
  accessModes:
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
