# Secrets - K8s Configuration
# https://kubernetes.io/docs/concepts/configuration/secret/


# MongoDB: Used by Voting Service and WebSocket Service
apiVersion: v1
kind: Secret
metadata:
  name: canvote-mongo-secret
  namespace: canvote
type: Opaque
# data:
#   # NOTE: All values must be base 64 encoded before being placed in this file and applying the configuration
    # # Host of MongoDB server; set to localhost by default
    # MONGO_HOST: "localhost"
    # # Port of MongoDB server; set to 27017 by default
    # MONGO_PORT: "2000"
    # # Username of user of MongoDB server; set to canvote by default
    # MONGO_USERNAME: "canvote"
    # # Name of database of MongoDB server; set to canvote by default
    # MONGO_DATABASE: "canvote"
    # MONGO_PASSWORD: 

---

# PostgreSQL: Postgres: Used by Auth Service
apiVersion: v1
kind: Secret
metadata:
  name: canvote-postgres-secret
  namespace: canvote
type: Opaque
# data:
#   # NOTE: All values must be base 64 encoded before being placed in this file and applying the configuration
    # # PostgreSQL username; set to canvote by default
    # DATABASE_USERNAME: "canvote"
    # # PostgreSQL Database; set to canvote-auth by default
    # DATABASE_DB: "canvote-auth"
    # # PostgreSQL Port; set to 5432 by default
    # DATABASE_PORT: "5432"
    # # PostgreSQL Host; set to localhost by default
    # DATABASE_HOST: "localhost"
    # DATABASE_PASSWORD: 

---

# Authentication: Used by Auth Service and Voting Service
apiVersion: v1
kind: Secret
metadata:
  name: canvote-auth-secret
  namespace: canvote
type: Opaque
# data:
#   # NOTE: All values must be base 64 encoded before being placed in this file and applying the configuration
#   INTERNAL_API_KEY:
#   JWT_SECRET_KEY:
#   JWT_ACTIVATION_SECRET_KEY:

---

# Email: Used by Auth Service
apiVersion: v1
kind: Secret
metadata:
  name: canvote-email-secret
  namespace: canvote
type: Opaque
# data:
#   # NOTE: All values must be base 64 encoded before being placed in this file and applying the configuration
#   EMAIL_MAILGUN_API_KEY:

---

# Administrator's Account: Used by Auth Service for initial user
apiVersion: v1
kind: Secret
metadata:
  name: canvote-admin-account-secret
  namespace: canvote
type: Opaque
# data:
#   # NOTE: All values must be base 64 encoded before being placed in this file and applying the configuration
#   ADMIN_ACCOUNT_EMAIL:
#   ADMIN_ACCOUNT_PASSWORD: