query Districts {
    districts {
        id
        name
        candidates {
            id
            name
            politicalParty {
                id
            }
        }
        geoJson
    }
}
