export enum AuthActionType {
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    USER_AUTHENTICATED_FROM_CHECK = 'USER_AUTHENTICATED_FROM_CHECK',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    INVALID_AUTH = 'INVALID_AUTH'
}
