export enum AuthActionType {
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    USER_AUTHENTICATED_FROM_CHECK = 'USER_AUTHENTICATED_FROM_CHECK',
    LOGOUT_FOR_USER = 'LOGOUT_FOR_USER',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
}
