{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "voting-service.serviceAccountName" . }}
  labels:
{{ include "voting-service.labels" . | nindent 4 }}
{{- end -}}
