query PoliticalPartyCandidates {
    politicalPartyCandidates {
        id
        name
        politicalParty {
            id
            name
            colour
        }
        picture {
            filename
            location
            mimetype
        }
    }
}
