mutation updatePoliticalPartyCandidate($id: ID!, $name: String!, $politicalParty: String!, $picture: Upload!, $district: String!) {
    updatePoliticalPartyCandidate(id: $id, name: $name, political_party: $politicalParty, picture: $picture, district: $district) {
        id
        name
        politicalParty {
            id
            name
            colour
        }
        picture {
            filename
            location
            mimetype
        }
    }
}
